### ISSUE TITLE
part's wont build

### ISSUE THREAD

**Issue by molekel** [alfikpl/ao486#1]
There are some files in the projects that don't exist in git. The processor compiles. But the SoC doesn't.
Perhaps you can check it on a freshly installed machine ?

best wishes

**Comment by alfikpl** [comment]
Did you generate the Qsys system before compiling the SoC project ?

Best regards,
Aleksander Osman.

**Comment by molekel** [comment]
No I don't think so. Hope I will get it to run. Thanks a lot for your help !!

best wishes
    Hannes Steindl

**Comment by ghost** [comment]
Aleksander, I am consistently amazed by your project. :-)  It is simply awesome.

**Comment by alfikpl** [comment]
Hannes, I hope you managed to build the project. Rick, thank you for your kind words.
