### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by apocsantos** [alfikpl/ao486#10]
Hi,

Would this run on a ALTERA Cyclone IV EP4CE6 FPGA Development Board Kit Altera EP4CE NIOSII ??

Regards

**Comment by alfikpl** [comment]
Hi,
I am afraid that this Cyclone IV FPGA is too small to run the ao486 design. The complete ao486 core uses up to 80% of the EP4CE115 device. If you are interested, have a look at https://github.com/MiSTer-devel/ao486_MiSTer. It's a much updated core.

Cheers,
Alek
