### ISSUE TITLE
Only find fdboot.img

### ISSUE THREAD

**Issue by JUSDJTIN** [alfikpl/ao486#7]
I have load bios and vgabios successfully. but when load the img file , I only find the **fdboot.img**, but I did not copy this file, no matter I copy freedos.img or not. It does not work. thanks
``sudo dd if=bios_vgabios.dat of=/dev/sdc0 bs=102400 seek=0
 sudo dd if=freedos1.1.img of=/dev/sdc0 bs=102400 seek=512
``

**Comment by alfikpl** [comment]
Hello JUSDJTIN,
Are you using the ao486_tool to generate the sd.dat file ?
The floppy image names are located in the header of the sd.dat file.
Cheers

**Comment by JUSDJTIN** [comment]
@alfikpl thank you very much , I have used the ao486_tool to generate the sd.dat. but  I only have the fdboot.img . Is the sd card's format have other requires？

**Comment by alfikpl** [comment]
I think that the ao486_tool collects all the files in the fd_1_44m directory. Check the SDGenerator.java source file.

**Comment by JUSDJTIN** [comment]
thank you very much @alfikpl I will check the source code.
